/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-12-03 15:24:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.img;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.service.impl.OcrService;
import poly.service.IOcrService;
import poly.dto.OcrDTO;
import static poly.util.CmmUtil.nvl;
import poly.controller.ImgController;

public final class img_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("poly.service.impl.OcrService");
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.controller.ImgController");
    _jspx_imports_classes.add("poly.service.IOcrService");
    _jspx_imports_classes.add("poly.dto.OcrDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String value = nvl((String)request.getAttribute("value"));
	ImgController ic = new ImgController();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>시험문제</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://jcrop-cdn.tapmodo.com/v0.9.12/css/jquery.Jcrop.min.css\" />\r\n");
      out.write("<!-- 추가 내용 시작-->\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/img.css\" />\r\n");
      out.write("<!--  추가 내용 끝-->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".qna__ques {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("canvas, #uploadFile, .qna__btn__edit, .qna__btn__cut, .qna__btn__enroll\r\n");
      out.write("\t{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://jcrop-cdn.tapmodo.com/v0.9.12/js/jquery.Jcrop.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../../js/pixelate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../../js/html2canvas.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      let jcropApi = null;\r\n");
      out.write("      let count = 0;\r\n");
      out.write("      // @breif 이미지 크롭 영역지정 UI 나타내기\r\n");
      out.write("      function imgCropDesignate() {\r\n");
      out.write("        let editWidth = $(\"#editImg\").width();\r\n");
      out.write("        let editHeight = $(\"#editImg\").height();\r\n");
      out.write("\r\n");
      out.write("        // @breif jcrop 실행시 크롭영역을 미리 세팅\r\n");
      out.write("\r\n");
      out.write("        let x1 = 0;\r\n");
      out.write("        let y1 = 0;\r\n");
      out.write("        let x2 = 100;\r\n");
      out.write("        let y2 = 100;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /*\r\n");
      out.write("        let x1 = window.screen.width / 2 - editWidth;\r\n");
      out.write("        let y1 = window.screen.height / 2 - editHeight;\r\n");
      out.write("        let x2 = editWidth / 1.5;\r\n");
      out.write("        let y2 = editHeight / 1.5;\r\n");
      out.write("        */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        // @breif jcrop 실행\r\n");
      out.write("        $(\"#editImg\").Jcrop(\r\n");
      out.write("          {\r\n");
      out.write("            bgFade: true,\r\n");
      out.write("            bgOpacity: 0.2,\r\n");
      out.write("            setSelect: [x1, y1, x2, y2],\r\n");
      out.write("            onSelect: updateCoords,\r\n");
      out.write("            maxSize: [10000,100]\r\n");
      out.write("          },\r\n");
      out.write("          function () {\r\n");
      out.write("            jcropApi = this;\r\n");
      out.write("          }\r\n");
      out.write("        );\r\n");
      out.write("\r\n");
      out.write("        $(\".jcrop-holder\").css(\"position\", \"absolute\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"right\", \"0\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"bottom\", \"0\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"width\", \"100%\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"height\", \"100%\");\r\n");
      out.write("\r\n");
      out.write("        $(\".qna__btn__edit\").css(\"display\", \"none\");\r\n");
      out.write("        $(\".qna__btn__cut\").css(\"display\", \"inline\");\r\n");
      out.write("        $(\".qna__btn__enroll\").css(\"display\", \"inline\");\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // @breif 지정된 크롭 한 영역( 좌표, 넓이, 높이 )의 값을 보관하는 함수\r\n");
      out.write("      function updateCoords(crap) {\r\n");
      out.write("        $(\"#xAxis\").val(crap.x);\r\n");
      out.write("        $(\"#yAxis\").val(crap.y);\r\n");
      out.write("        $(\"#wLength\").val(crap.w);\r\n");
      out.write("        $(\"#hLength\").val(crap.h);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // @breif 크롭한 영역 잘라내고 추출하기\r\n");
      out.write("      function imgCropApply() {\r\n");
      out.write("        if (parseInt($(\"#wLength\").val()) == \"NaN\") {\r\n");
      out.write("          alert(\"이미지를 크롭한 이후\\n자르기 버튼을 클릭하세요.\");\r\n");
      out.write("          return false;\r\n");
      out.write("          } else {\r\n");
      out.write("            for (cnt = 1; cnt < 6; cnt++) {\r\n");
      out.write("            let crop_img = \"#crop__img__0\" + cnt;\r\n");
      out.write("            let crop_id = document.querySelector(crop_img).src;\r\n");
      out.write("              if (crop_id !== undefined && crop_id !== \"\") continue;\r\n");
      out.write("            let edit_img = \"#editImg\";\r\n");
      out.write("            let crop_img_sel = document.querySelector(crop_img);\r\n");
      out.write("            //let imgArea_sel = document.querySelector(\".imgArea\");\r\n");
      out.write("            //let new_img = document.createElement(\"img\");\r\n");
      out.write("            //imgArea_sel.appendChild(new_img);\r\n");
      out.write("            //crop_img_sel.appendChild(new_img);\r\n");
      out.write("            //new_img.setAttribute(\"id\", crop_img);\r\n");
      out.write("\r\n");
      out.write("            let editImage = new Image();\r\n");
      out.write("            editImage.src = $(\"#editImg\").attr(\"src\");\r\n");
      out.write("\r\n");
      out.write("            editImage.onload = function () {\r\n");
      out.write("              // @breif 캔버스 위에 이미지 그리기\r\n");
      out.write("              let canvas = document.querySelector(\"canvas\");\r\n");
      out.write("              let canvasContext = canvas.getContext(\"2d\");\r\n");
      out.write("\r\n");
      out.write("              // @breif 캔버스 크기를 이미지 크기와 동일하게 지정\r\n");
      out.write("              canvas.width = $(\"#wLength\").val();\r\n");
      out.write("              canvas.height = $(\"#hLength\").val();\r\n");
      out.write("              canvasContext.drawImage(\r\n");
      out.write("                this,\r\n");
      out.write("                $(\"#xAxis\").val(), // 자르기를 시작할 x좌표\r\n");
      out.write("                $(\"#yAxis\").val(), // 자르기를 시작할 y좌표\r\n");
      out.write("                $(\"#wLength\").val(), // 잘라낸 이미지의 넓이\r\n");
      out.write("                $(\"#hLength\").val(), // 잘라낸 이미지의 높이\r\n");
      out.write("                0, // 캔버스에 이미지를 배치할 x좌표\r\n");
      out.write("                0, // 캔버스에 이미지를 배치할 y좌표\r\n");
      out.write("                $(\"#wLength\").val(), // 사용할 이미지의 넓이(이미지 스트레칭 또는 축소)\r\n");
      out.write("                $(\"#hLength\").val() // 사용할 이미지의 높이(이미지 스트레칭 또는 축소)\r\n");
      out.write("              );\r\n");
      out.write("\r\n");
      out.write("              // @breif 편집한 캔버스의 이미지를 화면에 출력한다.\r\n");
      out.write("              let dataURI = canvas.toDataURL(\"image/jpeg\");\r\n");
      out.write("              //let crop_id = document.getElementById(crop_img);\r\n");
      out.write("              let edit_id = document.querySelector(edit_img);\r\n");
      out.write("\r\n");
      out.write("              crop_img_sel.setAttribute(\"src\", dataURI);\r\n");
      out.write("              crop_img_sel.style.width = $(\"#wLength\").val();\r\n");
      out.write("              crop_img_sel.style.height = $(\"#hLength\").val();\r\n");
      out.write("              //$(\"#editImg\"+cnt).attr(\"src\", dataURI);\r\n");
      out.write("\r\n");
      out.write("              let temp_img = document.createElement(\"img\");\r\n");
      out.write("              temp_img.setAttribute(\"src\", \"../../../img/0\" + cnt + \".jpg\");\r\n");
      out.write("              temp_img.setAttribute(\"id\", \"shade__img__0\"+cnt);\r\n");
      out.write("\r\n");
      out.write("              temp_img.style.position = \"absolute\";\r\n");
      out.write("              //temp_left = parseInt($(\"#xAxis\").val()) + document.querySelector(\"#pic_id\").offsetLeft;\r\n");
      out.write("              //temp_img.style.left = temp_left + \"px\";\r\n");
      out.write("              temp_img.style.left = $(\"#xAxis\").val() + \"px\";\r\n");
      out.write("              temp_img.style.top = $(\"#yAxis\").val() + \"px\";\r\n");
      out.write("              temp_img.style.width = $(\"#wLength\").val() + \"px\";\r\n");
      out.write("              temp_img.style.height = $(\"#hLength\").val() + \"px\";\r\n");
      out.write("\r\n");
      out.write("              let temptemp = document.querySelector(\".qna__ques__pic\");\r\n");
      out.write("              temptemp.appendChild(temp_img);\r\n");
      out.write("              // 원본 이미지를 모자이크 크기만큼 그리기\r\n");
      out.write("              canvasContext.drawImage(\r\n");
      out.write("                canvas,\r\n");
      out.write("                $(\"#xAxis\").val(),\r\n");
      out.write("                $(\"#yAxis\").val(),\r\n");
      out.write("                $(\"#wLength\").val(),\r\n");
      out.write("                $(\"#hLength\").val()\r\n");
      out.write("              );\r\n");
      out.write("\r\n");
      out.write("              $(\".qna__ques\").css(\"position\", \"relative\");\r\n");
      out.write("\r\n");
      out.write("              // 이미지 사이즈 크기 조절 시에 대한 안티앨리어싱 끄기\r\n");
      out.write("              canvasContext.msImageSmoothingEnabled = false;\r\n");
      out.write("              canvasContext.mozImageSmoothingEnabled = false;\r\n");
      out.write("              canvasContext.webkitImageSmoothingEnabled = false;\r\n");
      out.write("              canvasContext.imageSmoothingEnabled = false;\r\n");
      out.write("\r\n");
      out.write("              // 이미지를 원본 사이즈로 다시 그리면 모자이크 완성\r\n");
      out.write("              canvasContext.drawImage(\r\n");
      out.write("                canvas,\r\n");
      out.write("                $(\"#xAxis\").val(),\r\n");
      out.write("                $(\"#yAxis\").val(),\r\n");
      out.write("                $(\"#wLength\").val(),\r\n");
      out.write("                $(\"#hLength\").val(),\r\n");
      out.write("                $(\"#xAxis\").val(),\r\n");
      out.write("                $(\"#yAxis\").val(),\r\n");
      out.write("                canvas.width,\r\n");
      out.write("                canvas.height\r\n");
      out.write("              );\r\n");
      out.write("\r\n");
      out.write("              /*var pixelate = new Pixelate(qrepImage, {\r\n");
      out.write("              amount: 0.7, // default: 0, pixelation percentage amount (range from 0 to 1)\r\n");
      out.write("          });*/\r\n");
      out.write("              //crop_id.onload = drawImageActualSize; // Draw when image has loaded\r\n");
      out.write("\r\n");
      out.write("              // @breif 이미지의 크기는 자른 이미지와 동일하게 지정\r\n");
      out.write("              //$(\"#editImg\"+cnt).css(\"width\", $(\"#wLength\").val());\r\n");
      out.write("\r\n");
      out.write("              //$(\"#editImg\"+cnt).css(\"height\", $(\"#hLength\").val());\r\n");
      out.write("              \r\n");
      out.write("\t\t \t\tconsole.log(\"dfdfsdfsdfsdf\"+dataURI);\r\n");
      out.write("\r\n");
      out.write("               $.ajax({\r\n");
      out.write("                url: '/img/img2.do',\r\n");
      out.write("                async : false,\r\n");
      out.write("                type : \"get\",\r\n");
      out.write("                data : {base64 : dataURI,\r\n");
      out.write("                        num : cnt},\r\n");
      out.write("                success: function(data){\r\n");
      out.write("                \tconsole.log(\"성공\");\r\n");
      out.write("                \tconsole.log(data);\r\n");
      out.write("                \tdocument.querySelector(\"#answer_0\"+cnt).setAttribute(\"value\", data);\r\n");
      out.write("\r\n");
      out.write("                \t\r\n");
      out.write("                }\r\n");
      out.write("              }) \r\n");
      out.write("              \r\n");
      out.write("              //document.querySelector(\"#answer_0\"+cnt).setAttribute(\"value\", data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("              imgCropDesignate();\r\n");
      out.write("\r\n");
      out.write("            };\r\n");
      out.write("            \r\n");
      out.write("              \r\n");
      out.write("              //document.querySelector(\"#answer_0\"+cnt).setAttribute(\"value\", data);\r\n");
      out.write("            //$(\"#cutBtn\").css(\"display\", \"none\");\r\n");
      out.write("\r\n");
      out.write("            // @details JCROP을 종료한다.\r\n");
      out.write("            jcropApi.destroy();\r\n");
      out.write("            jcropApi = null;\r\n");
      out.write("            break;\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /*  function drawImageActualSize() {\r\n");
      out.write("    \t  // Use the intrinsic size of image in CSS pixels for the canvas element\r\n");
      out.write("    \t  canvas.width = this.naturalWidth;\r\n");
      out.write("    \t  canvas.height = this.naturalHeight;\r\n");
      out.write("\r\n");
      out.write("    \t  // Will draw the image as 300x227, ignoring the custom size of 60x45\r\n");
      out.write("    \t  // given in the constructor\r\n");
      out.write("    \t  canvasContext.drawImage(this, $(\"#xAxis\").val(), $(\"#yAxis\").val());\r\n");
      out.write("\r\n");
      out.write("    \t  // To use the custom size we'll have to specify the scale parameters \r\n");
      out.write("    \t  // using the element's width and height properties - lets draw one \r\n");
      out.write("    \t  // on top in the corner:\r\n");
      out.write("    \t  canvasContext.drawImage(this, $(\"#xAxis\").val(), $(\"#yAxis\").val(), $(\"#wLength\").val(), $(\"#hLength\").val(), $(\"#xAxis\").val(), $(\"#yAxis\").val(), canvas.width, canvas.height);\r\n");
      out.write("\t\t\t\r\n");
      out.write("    } */\r\n");
      out.write("      \r\n");
      out.write("      // @breif 이미지 업로드 함수\r\n");
      out.write("      function uploadImgFilePrinted(up) {\r\n");
      out.write("        // @details 업로드 파일 정보를 받아온다.\r\n");
      out.write("        \r\n");
      out.write("        let fileInfo = document.querySelector(\"#\"+up).files[0];\r\n");
      out.write("        //let fileInfo = document.getElementById(\"uploadFile\").files[0];\r\n");
      out.write("        let reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("        reader.onload = function () {\r\n");
      out.write("          // @details 업로드 이미지 출력\r\n");
      out.write("          $(\"#editImg\").attr(\"src\", reader.result);\r\n");
      out.write("\r\n");
      out.write("          // @details 이미지 크기를 제목 영역과 같게 출력\r\n");
      out.write("          //$(\"#editImg\").css(\"width\", $(\"h1\").width());\r\n");
      out.write("\r\n");
      out.write("          // @details 이미지 업로드 기능 제거, 추가 업로드 방지\r\n");
      out.write("          $(\"#editImg\").parent(\"a\").removeAttr(\"onClick\");\r\n");
      out.write("\r\n");
      out.write("          // @details 편집버튼 노출\r\n");
      out.write("          $(\".qna__btn__edit\").css(\"display\", \"inline\");\r\n");
      out.write("\r\n");
      out.write("          $(\".qna__ques\").css(\"postion\", \"relative\");\r\n");
      out.write("\r\n");
      out.write("          //$(\"#editImg\").css(\"width\", \"470px\");\r\n");
      out.write("          //$(\"#editImg\").css(\"height\", \"664.58px\");\r\n");
      out.write("          //$(\"#editImg\").css(\"height\", \"100%\");\r\n");
      out.write("          //$(\"#editImg\").css(\"width\", \"70.72135785%\");\r\n");
      out.write("          //$(\"#editImg\").css(\"width\", $(\"#editImg\").height() / 1.414 +\"px\");\r\n");
      out.write("          //$(\"#editImg\").css(\"padding-bottom\", \"70.72135785%\");\r\n");
      out.write("\r\n");
      out.write("          canvasDrawImage(function () {\r\n");
      out.write("            alert(\"이미지 업로드가 완료되었습니다.\");\r\n");
      out.write("          });\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        if (fileInfo) {\r\n");
      out.write("          // @details readAsDataURL을 통해 업로드한 파일의 URL을 읽어 들인다.\r\n");
      out.write("          reader.readAsDataURL(fileInfo);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // @breif 캔버스 이미지 생성\r\n");
      out.write("      function canvasDrawImage(callback) {\r\n");
      out.write("        let prepImage = new Image();\r\n");
      out.write("        prepImage.src = $(\"#editImg\").attr(\"src\");\r\n");
      out.write("\r\n");
      out.write("        prepImage.onload = function () {\r\n");
      out.write("          // @details 캔버스 위에 이미지 그리기\r\n");
      out.write("          // jQuery(\"canvas\") 와같은 명령은 사용할 수 없다.\r\n");
      out.write("          let canvas = document.querySelector(\"canvas\");\r\n");
      out.write("          let canvasContext = canvas.getContext(\"2d\");\r\n");
      out.write("\r\n");
      out.write("          canvas.width = $(\"#editImg\").width();\r\n");
      out.write("          canvas.height = $(\"#editImg\").height();\r\n");
      out.write("          canvasContext.drawImage(\r\n");
      out.write("            this,\r\n");
      out.write("            0,\r\n");
      out.write("            0,\r\n");
      out.write("            $(\"#editImg\").width(),\r\n");
      out.write("            $(\"#editImg\").height()\r\n");
      out.write("          );\r\n");
      out.write("\r\n");
      out.write("          // @details 캔버스의 이미지\r\n");
      out.write("          let dataURI = canvas.toDataURL(\"image/jpeg\");\r\n");
      out.write("          $(\"#editImg\").attr(\"src\", dataURI);\r\n");
      out.write("\r\n");
      out.write("          callback();\r\n");
      out.write("        };\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // 되돌리기\r\n");
      out.write("      function cancelCropImage(cnt) {\r\n");
      out.write("        \r\n");
      out.write("        let crp_img = \"#crop__img__\" + cnt;\r\n");
      out.write("        document.querySelector(crp_img).removeAttribute('src');\r\n");
      out.write("\r\n");
      out.write("        let shade_img = \"#shade__img__\" + cnt;\r\n");
      out.write("        let shade_id = document.querySelector(shade_img);\r\n");
      out.write("        let input_value = \"#answer_\" + cnt;\r\n");
      out.write("        let input_id = document.querySelector(input_value);\r\n");
      out.write("        shade_id.parentNode.removeChild(shade_id);\r\n");
      out.write("        input_id.removeAttribute('value');\r\n");
      out.write("        //$('shade__img__' + cnt).remove();\r\n");
      out.write("        //$( crp_img ).removeAttr( 'src' );\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        /*if (cnt > 0) {\r\n");
      out.write("          let cropImg = document.querySelector(\".crop_img\");\r\n");
      out.write("          let shade = document.querySelector(\".qna__ques\");\r\n");
      out.write("\r\n");
      out.write("          cropImg.removeChild(cropImg.lastChild);\r\n");
      out.write("          shade.removeChild(shade.lastChild);\r\n");
      out.write("\r\n");
      out.write("          cnt--;\r\n");
      out.write("        }*/\r\n");
      out.write("\r\n");
      out.write("        //if (cnt == 0) $(\".btn\").css(\"width\", \"50%\");\r\n");
      out.write("        //else $(\".btn\").css(\"width\", \"10%\");\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // 전체 스샷\r\n");
      out.write("      /* function bodyShot() { \r\n");
      out.write("    \thtml2canvas(document.body)\r\n");
      out.write("    \t//document에서 body 부분을 스크린샷을 함.\r\n");
      out.write("    \t.then(\r\n");
      out.write("    \t\t\tfunction (canvas) {\r\n");
      out.write("    \t\t\t\t//canvas 결과값을 drawImg 함수를 통해서\r\n");
      out.write("    \t\t\t\t//결과를 canvas 넘어줌.\r\n");
      out.write("    \t\t\t\t//png의 결과 값\r\n");
      out.write("    \t\t\t\tdrawImg(canvas.toDataURL('image/png'));\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t//appendchild 부분을 주석을 풀게 되면 body\r\n");
      out.write("    \t\t\t\t//document.body.appendChild(canvas);\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t//특별부록 파일 저장하기 위한 부분.\r\n");
      out.write("    \t\t\t\tsaveAs(canvas.toDataURL(), 'file-name.png');\r\n");
      out.write("    \t\t\t\t}).catch(function (err) {\r\n");
      out.write("    \t\t\t\t\tconsole.log(err);\r\n");
      out.write("    \t\t\t\t\t});\r\n");
      out.write("    \t} */\r\n");
      out.write("\r\n");
      out.write("      // 부분 스샷\r\n");
      out.write("      function partShot() {\r\n");
      out.write("        //특정부분 스크린샷\r\n");
      out.write("        html2canvas(document.querySelector(\".qna__ques\"))\r\n");
      out.write("          //id container 부분만 스크린샷\r\n");
      out.write("          .then(function (canvas) {\r\n");
      out.write("            //jpg 결과값\r\n");
      out.write("            drawImg(canvas.toDataURL(\"image/jpeg\"));\r\n");
      out.write("            //이미지 저장\r\n");
      out.write("            saveAs(canvas.toDataURL(), \"file-name.jpg\");\r\n");
      out.write("          })\r\n");
      out.write("          .catch(function (err) {\r\n");
      out.write("            console.log(err);\r\n");
      out.write("          });\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function drawImg(imgData) {\r\n");
      out.write("        console.log(imgData);\r\n");
      out.write("        //imgData의 결과값을 console 로그롤 보실 수 있습니다.\r\n");
      out.write("        return new Promise(\r\n");
      out.write("          function resolve() {\r\n");
      out.write("            //내가 결과 값을 그릴 canvas 부분 설정\r\n");
      out.write("            var canvas = document.getElementById(\"canvas\");\r\n");
      out.write("            var ctx = canvas.getContext(\"2d\");\r\n");
      out.write("            //canvas의 뿌려진 부분 초기화\r\n");
      out.write("            ctx.clearRect(0, 0, canvas.width, canvas.height);\r\n");
      out.write("\r\n");
      out.write("            var imageObj = new Image();\r\n");
      out.write("            imageObj.onload = function () {\r\n");
      out.write("              ctx.drawImage(imageObj, 10, 10);\r\n");
      out.write("              //canvas img를 그리겠다.\r\n");
      out.write("            };\r\n");
      out.write("            imageObj.src = imgData;\r\n");
      out.write("            //그릴 image데이터를 넣어준다.\r\n");
      out.write("          },\r\n");
      out.write("          function reject() {}\r\n");
      out.write("        );\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function saveAs(uri, filename) {\r\n");
      out.write("        var link = document.createElement(\"a\");\r\n");
      out.write("        if (typeof link.download === \"string\") {\r\n");
      out.write("          link.href = uri;\r\n");
      out.write("          link.download = filename;\r\n");
      out.write("          document.body.appendChild(link);\r\n");
      out.write("          link.click();\r\n");
      out.write("          document.body.removeChild(link);\r\n");
      out.write("        } else {\r\n");
      out.write("          window.open(uri);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type=\"hidden\" id=\"xAxis\" value=\"0\" placeholder=\"선택영역의_x좌표\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"yAxis\" value=\"0\" placeholder=\"선택영역의_y좌표\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"wLength\" value=\"0\" placeholder=\"선택영역의_w넓이\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"hLength\" value=\"0\" placeholder=\"선택영역의_h높이\" />\r\n");
      out.write("\t<input type=\"file\" id=\"uploadFile\"\r\n");
      out.write("\t\tonChange=\"uploadImgFilePrinted('uploadFile');\" accept=\"image/*\" />\r\n");
      out.write("\t<div class=\"qna\" id=\"qna\">\r\n");
      out.write("\t\t<div class=\"qna qna__ques_o\" id=\"qna__ques\">\r\n");
      out.write("\t\t\t<div class=\"qna__ques qna__ques__title title\">\r\n");
      out.write("\t\t\t\t<h3 class=\"title\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">과목</a> - <a href=\"#\">소제목</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"qna__ques qna__ques__pic\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" onClick=\"$('#uploadFile').click();\"\r\n");
      out.write("\t\t\t\t\tid=\"pic_id\"> <img id=\"editImg\" src=\"../../../img/user.png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<canvas id=\"canvas\"></canvas>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"btn qna qna__btn\" id=\"qna__btn\">\r\n");
      out.write("\t\t\t<div class=\"btn qna__btn qna__btn__edit\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"편집\" onClick=\"imgCropDesignate();\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"btn qna__btn qna__btn__upload\">\r\n");
      out.write("\t\t\t\t<input type=\"file\" name=\"file\" id=\"uploadAnother\"\r\n");
      out.write("\t\t\t\t\tonChange=\"uploadImgFilePrinted('uploadAnother');\" accept=\"image/*\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: none;\" />\r\n");
      out.write("\t\t\t\t<div class=\"button\" onClick=\"$('#uploadAnother').click();\">업로드</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"btn qna__btn qna__btn__cut\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"자르기\" onClick=\"imgCropApply();\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"btn qna__btn qna__btn__enroll\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"등록\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"btn qna__btn qna__btn__cap\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"임시캡쳐\" onclick=\"partShot();\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"qna qna__ans\" id=\"qna__ans\">\r\n");
      out.write("\t\t\t<div class=\"qna__ans qna__ans__title title\">\r\n");
      out.write("\t\t\t\t<h3 class=\"title\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">문제리스트</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"qna__ans qna__ans__group\" id=\"qna__ans__group\">\r\n");
      out.write("\t\t\t\t<div class=\"qna__ans__grp ans__group__01\">\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__num\">01</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__01\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"crop__img__01\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__arrow\">-></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"qna__ans__group__answer\"> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"answer\" id=\"answer_01\" />\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"btn qna__ans__group qna__ans__group__btn\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"지우기\" class=\"btn btn__cut btn__cut__01\"\r\n");
      out.write("\t\t\t\t\t\tonClick=\"cancelCropImage('01');\" />\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"qna__ans__grp ans__group__02\">\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__num\">02</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__02\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"crop__img__02\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__arrow\">-></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"qna__ans__group__answer\"> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"answer\" id=\"answer_02\" />\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"btn qna__ans__group qna__ans__group__btn\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"지우기\" class=\"btn btn__cut btn__cut__02\"\r\n");
      out.write("\t\t\t\t\t\tonClick=\"cancelCropImage('02');\" />\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"qna__ans__grp ans__group__03\">\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__num\">03</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__03\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"crop__img__03\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__arrow\">-></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"qna__ans__group__answer\"> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"answer\" id=\"answer_03\" />\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"btn qna__ans__group qna__ans__group__btn\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"지우기\" class=\"btn btn__cut btn__cut__03\"\r\n");
      out.write("\t\t\t\t\t\tonClick=\"cancelCropImage('03');\" />\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"qna__ans__grp ans__group__04\">\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__num\">04</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__04\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"crop__img__04\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__arrow\">-></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"qna__ans__group__answer\"> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"answer\" id=\"answer_04\" />\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"btn qna__ans__group qna__ans__group__btn\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"지우기\" class=\"btn btn__cut btn__cut__04\"\r\n");
      out.write("\t\t\t\t\t\tonClick=\"cancelCropImage('04');\" />\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"qna__ans__grp ans__group__05\">\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__num\">05</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__05\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"crop__img__05\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"qna__ans__group__arrow\">-></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"qna__ans__group__answer\"> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"answer\" id=\"answer_05\" />\r\n");
      out.write("\t\t\t\t\t</span> <span class=\"btn qna__ans__group qna__ans__group__btn\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"지우기\" class=\"btn btn__cut btn__cut__05\"\r\n");
      out.write("\t\t\t\t\t\tonClick=\"cancelCropImage('05');\" />\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--\r\n");
      out.write("      <div class=\"imgArea\" style=\"float: left; width: 50%\">\r\n");
      out.write("        <a href=\"javascript:;\" onClick=\"$('#uploadFile').click();\" id=\"pic_id\">\r\n");
      out.write("          <img id=\"editImg\" src=\"../../../img/user.png\"/ width=\"50%\"\r\n");
      out.write("          height=\"50%\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <br />\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"crop_img\" style=\"float: right; width: 40%\"></div>\r\n");
      out.write("      <div class=\"btn\" style=\"float: right; width: 50%\">\r\n");
      out.write("        <input\r\n");
      out.write("          id=\"editBtn\"\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          onClick=\"imgCropDesignate();\"\r\n");
      out.write("          value=\"편집\"\r\n");
      out.write("        />\r\n");
      out.write("        <input\r\n");
      out.write("          id=\"cutBtn\"\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          onClick=\"imgCropApply();\"\r\n");
      out.write("          value=\"자르기\"\r\n");
      out.write("          style=\"text-align: center\"\r\n");
      out.write("        />\r\n");
      out.write("        <br />\r\n");
      out.write("        <input\r\n");
      out.write("          id=\"canBtn\"\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          onClick=\"cancelCropImage();\"\r\n");
      out.write("          value=\"되돌리기\"\r\n");
      out.write("          style=\"text-align: center\"\r\n");
      out.write("        />\r\n");
      out.write("        -->\r\n");
      out.write("\t\t<!-- 전체 부분\r\n");
      out.write("        <button onclick=bodyShot()>bodyShot</button>-->\r\n");
      out.write("\t\t<!-- 일부분-->\r\n");
      out.write("\t\t<!--\r\n");
      out.write("        <button onclick=\"partShot()\">partShot</button>\r\n");
      out.write("-->\r\n");
      out.write("\t\t<!-- 결과화면을 그려줄 canvas \r\n");
      out.write("        <canvas id=\"canvas\" width=\"900\" height=\"600\" style=\"border:1px solid #d3d3d3;\"></canvas>-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--\r\n");
      out.write("      <canvas id=\"canvas\"></canvas>\r\n");
      out.write("      -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
