/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-12-06 09:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.img;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.service.impl.OcrService;
import poly.service.IOcrService;
import poly.dto.OcrDTO;
import static poly.util.CmmUtil.nvl;
import poly.controller.ImgController;

public final class img_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("poly.service.impl.OcrService");
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.controller.ImgController");
    _jspx_imports_classes.add("poly.service.IOcrService");
    _jspx_imports_classes.add("poly.dto.OcrDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String value = nvl((String) request.getAttribute("value"));
ImgController ic = new ImgController();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>시험문제</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://jcrop-cdn.tapmodo.com/v0.9.12/css/jquery.Jcrop.min.css\" />\r\n");
      out.write("<!-- 추가 내용 시작-->\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/img.css\" />\r\n");
      out.write("<link type=\"text/css\"\r\n");
      out.write("\thref=\"https://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/style.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/style2.css\" />\r\n");
      out.write("<!--  추가 내용 끝-->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".qna__ques {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("canvas, #uploadFile, .qna__btn__edit, .qna__btn__cut, .qna__btn__enroll\r\n");
      out.write("\t{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfont-family: \"Black Han Sans\", \"Oswald\", Verdana, sans-serif;\r\n");
      out.write("\tbackground-image: url(\"/img/pasta2.jpg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"] {\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tfont-family: \"Black Han Sans\", \"Oswald\", Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://jcrop-cdn.tapmodo.com/v0.9.12/js/jquery.Jcrop.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/pixelate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/html2canvas.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      let jcropApi = null;\r\n");
      out.write("      // @breif 이미지 크롭 영역지정 UI 나타내기\r\n");
      out.write("      function imgCropDesignate() {\r\n");
      out.write("        let editWidth = $(\"#editImg\").width();\r\n");
      out.write("        let editHeight = $(\"#editImg\").height();\r\n");
      out.write("\r\n");
      out.write("        // @breif jcrop 실행시 크롭영역을 미리 세팅\r\n");
      out.write("\r\n");
      out.write("        let x1 = 0;\r\n");
      out.write("        let y1 = 0;\r\n");
      out.write("        let x2 = 100;\r\n");
      out.write("        let y2 = 100;\r\n");
      out.write("\r\n");
      out.write("        // @breif jcrop 실행\r\n");
      out.write("        $(\"#editImg\").Jcrop(\r\n");
      out.write("          {\r\n");
      out.write("            bgFade: true,\r\n");
      out.write("            bgOpacity: 0.2,\r\n");
      out.write("            setSelect: [x1, y1, x2, y2],\r\n");
      out.write("            onSelect: updateCoords,\r\n");
      out.write("            maxSize: [10000,50]\r\n");
      out.write("          },\r\n");
      out.write("          function () {\r\n");
      out.write("            jcropApi = this;\r\n");
      out.write("          }\r\n");
      out.write("        );\r\n");
      out.write("\r\n");
      out.write("        $(\".jcrop-holder\").css(\"position\", \"absolute\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"right\", \"0\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"bottom\", \"0\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"width\", \"100%\");\r\n");
      out.write("        $(\".jcrop-holder\").css(\"height\", \"100%\");\r\n");
      out.write("\r\n");
      out.write("        $(\".qna__btn__edit\").css(\"display\", \"none\");\r\n");
      out.write("        $(\".qna__btn__cut\").css(\"display\", \"inline\");\r\n");
      out.write("        $(\".qna__btn__enroll\").css(\"display\", \"inline\");\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // @breif 지정된 크롭 한 영역( 좌표, 넓이, 높이 )의 값을 보관하는 함수\r\n");
      out.write("      function updateCoords(crap) {\r\n");
      out.write("        $(\"#xAxis\").val(crap.x);\r\n");
      out.write("        $(\"#yAxis\").val(crap.y);\r\n");
      out.write("        $(\"#wLength\").val(crap.w);\r\n");
      out.write("        $(\"#hLength\").val(crap.h);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // @breif 크롭한 영역 잘라내고 추출하기\r\n");
      out.write("      function imgCropApply(lang) {\r\n");
      out.write("        if (parseInt($(\"#wLength\").val()) == \"NaN\") {\r\n");
      out.write("          alert(\"이미지를 크롭한 이후\\n자르기 버튼을 클릭하세요.\");\r\n");
      out.write("          return false;\r\n");
      out.write("          } else {\r\n");
      out.write("            for (cnt = 1; cnt < 6; cnt++) {\r\n");
      out.write("            let crop_img = \"#crop__img__0\" + cnt;\r\n");
      out.write("            let crop_id = document.querySelector(crop_img).src;\r\n");
      out.write("              if (crop_id !== undefined && crop_id !== \"\") continue;\r\n");
      out.write("            partShot();\r\n");
      out.write("            let edit_img = \"#editImg\";\r\n");
      out.write("            let crop_img_sel = document.querySelector(crop_img);\r\n");
      out.write("\r\n");
      out.write("            let editImage = new Image();\r\n");
      out.write("            editImage.src = $(\"#editImg\").attr(\"src\");\r\n");
      out.write("\r\n");
      out.write("            editImage.onload = function () {\r\n");
      out.write("              // @breif 캔버스 위에 이미지 그리기\r\n");
      out.write("              let canvas = document.querySelector(\"canvas\");\r\n");
      out.write("              let canvasContext = canvas.getContext(\"2d\");\r\n");
      out.write("\r\n");
      out.write("              // @breif 캔버스 크기를 이미지 크기와 동일하게 지정\r\n");
      out.write("              canvas.width = $(\"#wLength\").val();\r\n");
      out.write("              canvas.height = $(\"#hLength\").val();\r\n");
      out.write("              canvasContext.drawImage(\r\n");
      out.write("                this,\r\n");
      out.write("                $(\"#xAxis\").val(), // 자르기를 시작할 x좌표\r\n");
      out.write("                $(\"#yAxis\").val(), // 자르기를 시작할 y좌표\r\n");
      out.write("                $(\"#wLength\").val(), // 잘라낸 이미지의 넓이\r\n");
      out.write("                $(\"#hLength\").val(), // 잘라낸 이미지의 높이\r\n");
      out.write("                0, // 캔버스에 이미지를 배치할 x좌표\r\n");
      out.write("                0, // 캔버스에 이미지를 배치할 y좌표\r\n");
      out.write("                $(\"#wLength\").val(), // 사용할 이미지의 넓이(이미지 스트레칭 또는 축소)\r\n");
      out.write("                $(\"#hLength\").val() // 사용할 이미지의 높이(이미지 스트레칭 또는 축소)\r\n");
      out.write("              );\r\n");
      out.write("\r\n");
      out.write("              // @breif 편집한 캔버스의 이미지를 화면에 출력한다.\r\n");
      out.write("              let dataURI = canvas.toDataURL(\"image/jpeg\");\r\n");
      out.write("              let edit_id = document.querySelector(edit_img);\r\n");
      out.write("\r\n");
      out.write("              crop_img_sel.setAttribute(\"src\", dataURI);\r\n");
      out.write("              crop_img_sel.style.width = $(\"#wLength\").val();\r\n");
      out.write("              crop_img_sel.style.height = $(\"#hLength\").val();\r\n");
      out.write("              //$(\"#editImg\"+cnt).attr(\"src\", dataURI);\r\n");
      out.write("\r\n");
      out.write("              let temp_img = document.createElement(\"img\");\r\n");
      out.write("              temp_img.setAttribute(\"src\", \"../../../img/0\" + cnt + \".png\");\r\n");
      out.write("              temp_img.setAttribute(\"id\", \"shade__img__0\"+cnt);\r\n");
      out.write("\r\n");
      out.write("              temp_img.style.position = \"absolute\";\r\n");
      out.write("              temp_img.style.left = $(\"#xAxis\").val() + \"px\";\r\n");
      out.write("              temp_img.style.top = $(\"#yAxis\").val() + \"px\";\r\n");
      out.write("              temp_img.style.width = $(\"#wLength\").val() + \"px\";\r\n");
      out.write("              temp_img.style.height = $(\"#hLength\").val() + \"px\";\r\n");
      out.write("\r\n");
      out.write("              let temptemp = document.querySelector(\".qna__ques__pic\");\r\n");
      out.write("              temptemp.appendChild(temp_img);\r\n");
      out.write("              // 원본 이미지를 모자이크 크기만큼 그리기\r\n");
      out.write("              canvasContext.drawImage(\r\n");
      out.write("                canvas,\r\n");
      out.write("                $(\"#xAxis\").val(),\r\n");
      out.write("                $(\"#yAxis\").val(),\r\n");
      out.write("                $(\"#wLength\").val(),\r\n");
      out.write("                $(\"#hLength\").val()\r\n");
      out.write("              );\r\n");
      out.write("\r\n");
      out.write("              $(\".qna__ques\").css(\"position\", \"relative\");\r\n");
      out.write("\r\n");
      out.write("              // 이미지 사이즈 크기 조절 시에 대한 안티앨리어싱 끄기\r\n");
      out.write("              canvasContext.msImageSmoothingEnabled = false;\r\n");
      out.write("              canvasContext.mozImageSmoothingEnabled = false;\r\n");
      out.write("              canvasContext.webkitImageSmoothingEnabled = false;\r\n");
      out.write("              canvasContext.imageSmoothingEnabled = false;\r\n");
      out.write("\r\n");
      out.write("              // 이미지를 원본 사이즈로 다시 그리면 모자이크 완성\r\n");
      out.write("              canvasContext.drawImage(\r\n");
      out.write("                canvas,\r\n");
      out.write("                $(\"#xAxis\").val(),\r\n");
      out.write("                $(\"#yAxis\").val(),\r\n");
      out.write("                $(\"#wLength\").val(),\r\n");
      out.write("                $(\"#hLength\").val(),\r\n");
      out.write("                $(\"#xAxis\").val(),\r\n");
      out.write("                $(\"#yAxis\").val(),\r\n");
      out.write("                canvas.width,\r\n");
      out.write("                canvas.height\r\n");
      out.write("              );\r\n");
      out.write("\r\n");
      out.write("               $.ajax({\r\n");
      out.write("                url: '/img/img2.do',\r\n");
      out.write("                async : true,\r\n");
      out.write("                type : \"post\",\r\n");
      out.write("                data : {base64 : dataURI,\r\n");
      out.write("                        num : cnt,\r\n");
      out.write("                        lang : lang},\r\n");
      out.write("                success: function(data){\r\n");
      out.write("                \tconsole.log(\"성공\");\r\n");
      out.write("                \tconsole.log(data);\r\n");
      out.write("                \tlet decodedata = decodeURI(data);\r\n");
      out.write("                \tconsole.log(decodedata);\r\n");
      out.write("                \tdocument.querySelector('#answer_0'+cnt).setAttribute('value', data);\r\n");
      out.write("                \tdocument.querySelector('#cropImgSrc0'+cnt).setAttribute('value', dataURI);\r\n");
      out.write("                }\r\n");
      out.write("              }) \r\n");
      out.write("\r\n");
      out.write("              imgCropDesignate();\r\n");
      out.write("\r\n");
      out.write("            };\r\n");
      out.write("            \r\n");
      out.write("            // @details JCROP을 종료한다.\r\n");
      out.write("            jcropApi.destroy();\r\n");
      out.write("            jcropApi = null;\r\n");
      out.write("            break;\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // @breif 이미지 업로드 함수\r\n");
      out.write("      function uploadImgFilePrinted(up) {\r\n");
      out.write("        // @details 업로드 파일 정보를 받아온다.\r\n");
      out.write("        \r\n");
      out.write("        let fileInfo = document.querySelector(\"#\"+up).files[0];\r\n");
      out.write("        //let fileInfo = document.getElementById(\"uploadFile\").files[0];\r\n");
      out.write("        let reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("        let jcrop = document.querySelector('.jcrop-holder');\r\n");
      out.write("        if (jcrop !== null) {\r\n");
      out.write("        \tjcrop.parentNode.removeChild(jcrop);\r\n");
      out.write("            jcropApi.destroy();\r\n");
      out.write("            jcropApi = null;\r\n");
      out.write("        }\r\n");
      out.write("        reader.onload = function () {\r\n");
      out.write("          // @details 업로드 이미지 출력\r\n");
      out.write("          $(\"#editImg\").attr(\"src\", reader.result);\r\n");
      out.write("\r\n");
      out.write("          // @details 이미지 크기를 제목 영역과 같게 출력\r\n");
      out.write("          //$(\"#editImg\").css(\"width\", $(\"h1\").width());\r\n");
      out.write("\r\n");
      out.write("          // @details 이미지 업로드 기능 제거, 추가 업로드 방지\r\n");
      out.write("          $(\"#editImg\").parent(\"a\").removeAttr(\"onClick\");\r\n");
      out.write("\r\n");
      out.write("          // @details 편집버튼 노출\r\n");
      out.write("          $(\".qna__btn__edit\").css(\"display\", \"inline\");\r\n");
      out.write("\r\n");
      out.write("          $(\".qna__ques\").css(\"postion\", \"relative\");\r\n");
      out.write("\r\n");
      out.write("          canvasDrawImage(function () {\r\n");
      out.write("            alert(\"이미지 업로드가 완료되었습니다.\");\r\n");
      out.write("          });\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        if (fileInfo) {\r\n");
      out.write("          // @details readAsDataURL을 통해 업로드한 파일의 URL을 읽어 들인다.\r\n");
      out.write("          reader.readAsDataURL(fileInfo);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // @breif 캔버스 이미지 생성\r\n");
      out.write("      function canvasDrawImage(callback) {\r\n");
      out.write("        let prepImage = new Image();\r\n");
      out.write("        prepImage.src = $(\"#editImg\").attr(\"src\");\r\n");
      out.write("\r\n");
      out.write("        prepImage.onload = function () {\r\n");
      out.write("          // @details 캔버스 위에 이미지 그리기\r\n");
      out.write("          // jQuery(\"canvas\") 와같은 명령은 사용할 수 없다.\r\n");
      out.write("          let canvas = document.querySelector(\"canvas\");\r\n");
      out.write("          let canvasContext = canvas.getContext(\"2d\");\r\n");
      out.write("\r\n");
      out.write("          $('#editImg').css(\"width\",\"100%\");\r\n");
      out.write("          $('#editImg').css(\"height\",\"100%\");\r\n");
      out.write("          \r\n");
      out.write("          canvas.width = $(\"#editImg\").width();\r\n");
      out.write("          canvas.height = $(\"#editImg\").height();\r\n");
      out.write("          canvasContext.drawImage(\r\n");
      out.write("            this,\r\n");
      out.write("            0,\r\n");
      out.write("            0,\r\n");
      out.write("            $(\"#editImg\").width(),\r\n");
      out.write("            $(\"#editImg\").height()\r\n");
      out.write("          );\r\n");
      out.write("\r\n");
      out.write("          // @details 캔버스의 이미지\r\n");
      out.write("          let dataURI = canvas.toDataURL(\"image/jpeg\");\r\n");
      out.write("          $(\"#editImg\").attr(\"src\", dataURI);\r\n");
      out.write("\r\n");
      out.write("          callback();\r\n");
      out.write("        };\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // 되돌리기\r\n");
      out.write("      function cancelCropImage(cnt) {\r\n");
      out.write("        \r\n");
      out.write("        let crp_img = \"#crop__img__\" + cnt;\r\n");
      out.write("        if (document.querySelector(crp_img).src === null || document.querySelector(crp_img).src === \"\") return;\r\n");
      out.write("        document.querySelector(crp_img).removeAttribute('src');\r\n");
      out.write("\r\n");
      out.write("        let shade_img = \"#shade__img__\" + cnt;\r\n");
      out.write("        let shade_id = document.querySelector(shade_img);\r\n");
      out.write("        let input_value = \"#answer_\" + cnt;\r\n");
      out.write("        let input_id = document.querySelector(input_value);\r\n");
      out.write("        shade_id.parentNode.removeChild(shade_id);\r\n");
      out.write("        input_id.removeAttribute('value');\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // 부분 스샷\r\n");
      out.write("      function partShot() {\r\n");
      out.write("        //특정부분 스크린샷\r\n");
      out.write("        html2canvas(document.querySelector(\".qna__ques__pic\"))\r\n");
      out.write("          //id container 부분만 스크린샷\r\n");
      out.write("          .then(function (canvas) {\r\n");
      out.write("            //jpg 결과값\r\n");
      out.write("            drawImg(canvas.toDataURL(\"image/jpeg\"));\r\n");
      out.write("            //이미지 저장\r\n");
      out.write("            //saveAs(canvas.toDataURL(), \"file-name.jpg\");\r\n");
      out.write("          })\r\n");
      out.write("          .catch(function (err) {\r\n");
      out.write("            console.log(err);\r\n");
      out.write("          });\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function drawImg(imgData) {\r\n");
      out.write("        console.log(imgData);\r\n");
      out.write("        //imgData의 결과값을 console 로그롤 보실 수 있습니다.\r\n");
      out.write("        return new Promise(\r\n");
      out.write("          function resolve() {\r\n");
      out.write("            //내가 결과 값을 그릴 canvas 부분 설정\r\n");
      out.write("            var canvas = document.getElementById(\"canvas\");\r\n");
      out.write("            var ctx = canvas.getContext(\"2d\");\r\n");
      out.write("            //canvas의 뿌려진 부분 초기화\r\n");
      out.write("            ctx.clearRect(0, 0, canvas.width, canvas.height);\r\n");
      out.write("\r\n");
      out.write("            var imageObj = new Image();\r\n");
      out.write("            imageObj.onload = function () {\r\n");
      out.write("              ctx.drawImage(imageObj, 10, 10);\r\n");
      out.write("              //canvas img를 그리겠다.\r\n");
      out.write("            };\r\n");
      out.write("            imageObj.src = imgData;\r\n");
      out.write("            //그릴 image데이터를 넣어준다.\r\n");
      out.write("            document.querySelector('#editImgSrc').setAttribute('value', imageObj.src);\r\n");
      out.write("          },\r\n");
      out.write("          function reject() {}\r\n");
      out.write("        );\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function saveAs(uri, filename) {\r\n");
      out.write("        var link = document.createElement(\"a\");\r\n");
      out.write("        if (typeof link.download === \"string\") {\r\n");
      out.write("          link.href = uri;\r\n");
      out.write("          link.download = filename;\r\n");
      out.write("          document.body.appendChild(link);\r\n");
      out.write("          link.click();\r\n");
      out.write("          document.body.removeChild(link);\r\n");
      out.write("        } else {\r\n");
      out.write("          window.open(uri);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"bgcol\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"xAxis\" value=\"0\" placeholder=\"선택영역의_x좌표\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"yAxis\" value=\"0\" placeholder=\"선택영역의_y좌표\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"wLength\" value=\"0\" placeholder=\"선택영역의_w넓이\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"hLength\" value=\"0\" placeholder=\"선택영역의_h높이\" />\r\n");
      out.write("\t<input type=\"file\" id=\"uploadFile\"\r\n");
      out.write("\t\tonChange=\"uploadImgFilePrinted('uploadFile');\" accept=\"image/*\" />\r\n");
      out.write("\t<form action=\"/img/img/enrollment.do\" method=\"post\" id=\"formform\"\r\n");
      out.write("\t\tname=\"formform\">\r\n");
      out.write("\t\t<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\t\t\t<nav class=\"navbar-inner header\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/index.do\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"brand\" style=\"color: #f89406\">QUIZ GENERATOR</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav pull-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"nav-link\"> MYPAGE </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"nav-link\"> BOARD </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"nav-link\"> LOGOUT </a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"triangle-down center\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i id=\"toggle\" class=\"fa fa-chevron-down fa-2x isDown\"></i>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"qna\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"qna qna__ques_o\" id=\"qna__ques\">\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ques qna__ques__pic\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:;\" onClick=\"$('#uploadFile').click();\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"pic_id\"> <img id=\"editImg\" src=\"../../../img/user.png\">\r\n");
      out.write("\t\t\t\t\t\t</a> <input type=\"hidden\" id=\"editImgSrc\" name=\"editImgSrc\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<canvas id=\"canvas\"></canvas>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"qna qna__btn\" id=\"qna__btn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"btn qna__btn qna__btn__edit\"\r\n");
      out.write("\t\t\t\t\t\tonClick=\"imgCropDesignate();\">편집</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn qna__btn qna__btn__upload\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" name=\"file\" id=\"uploadAnother\"\r\n");
      out.write("\t\t\t\t\t\t\tonChange=\"uploadImgFilePrinted('uploadAnother');\"\r\n");
      out.write("\t\t\t\t\t\t\taccept=\"image/*\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"button\" onClick=\"$('#uploadAnother').click();\">업로드</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn qna__btn qna__btn__cut\">\r\n");
      out.write("\t\t\t\t\t\t<label> <input type=\"checkbox\" id=\"hangul\" name=\"lang\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"hangul\" />한글\r\n");
      out.write("\t\t\t\t\t\t</label> <br />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn qna__btn qna__btn__cut\"\r\n");
      out.write("\t\t\t\t\t\t\tonClick=\"imgCropApply($('#hangul').is(':checked'));\">자르기</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn qna__btn qna__btn__enroll\"\r\n");
      out.write("\t\t\t\t\t\tonClick=\"document.getElementById('formform').submit();\">등록</div>\r\n");
      out.write("\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t<div class=\"btn qna__btn qna__btn__cap\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"임시캡쳐\" onclick=\"partShot();\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"qna qna__ans\" id=\"qna__ans\">\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ans qna__ans__title title\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t- 한글은 한글 체크 / 숫자, 영어는 한글 체크 해제 <br /> - 색깔 영역을 더블 클릭하면 해당 가리개,\r\n");
      out.write("\t\t\t\t\t\t\t이미지가 지워집니다.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"qna__ans qna__ans__group\" id=\"qna__ans__group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"qna__ans__grp ans__group__01\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__num\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"colorShade\" src=\"/img/01.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tondblClick=\"cancelCropImage('01');\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__qna\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__01\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"crop__img__01\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"cropImgSrc01\" name=\"cropImgSrc01\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__answer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"answer\" id=\"answer_01\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"answer_01\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"qna__ans__grp ans__group__02\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__num\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"colorShade\" src=\"/img/02.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tondblClick=\"cancelCropImage('02');\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__qna\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"crop__img__02\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"cropImgSrc02\" name=\"cropImgSrc02\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__answer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"answer\" id=\"answer_02\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"answer_02\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"qna__ans__grp ans__group__03\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__num\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"colorShade\" src=\"/img/03.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tondblClick=\"cancelCropImage('03');\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__qna\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__03\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"crop__img__03\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"cropImgSrc03\" name=\"cropImgSrc03\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__answer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"answer\" id=\"answer_03\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"answer_03\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"qna__ans__grp ans__group__04\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__num\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"colorShade\" src=\"/img/04.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tondblClick=\"cancelCropImage('04');\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__qna\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__04\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"crop__img__04\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"cropImgSrc04\" name=\"cropImgSrc04\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__answer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"answer\" id=\"answer_04\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"answer_04\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"qna__ans__grp ans__group__05\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__num\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"colorShade\" src=\"/img/05.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tondblClick=\"cancelCropImage('05');\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"qna__ans__group__qna\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__pic qna__ans__group__pic__05\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"crop__img__05\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"cropImgSrc05\" name=\"cropImgSrc05\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"qna__ans__group__answer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"answer\" id=\"answer_05\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"answer_05\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
